### ISSUE TITLE
improve mobile view experience

### ISSUE THREAD

**Issue by bgalek** [allegro/hacktoberfest-dashboard#39]
Especially do something with tabs ;)

**Comment by jedlikowski** [comment]
I'll be working on improving the mobile view of the "Inspirations" tab:

![image](https://github.com/allegro/hacktoberfest-dashboard/assets/9341608/c9a6694a-60ae-4d04-ad59-4c148e72d34b)

**Comment by alan-rudzinski** [comment]
I will take care of tab view:

<img width="476" alt="image" src="https://github.com/user-attachments/assets/08189e84-8a69-4258-9beb-9438a679add0">
